### ISSUE TITLE
Couldn't open CUDA library libcupti.so.8.0. 

### ISSUE THREAD

**Issue by smolendawid** [google/seq2seq#180]
I have got error with such message:

> I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 8735 get requests, put_count=8686 evicted_count=1000 eviction_rate=0.115128 and unsatisfied allocation rate=0.13154
> I tensorflow/core/common_runtime/gpu/pool_allocator.cc:259] Raising pool_size_limit_ from 100 to 110
> INFO:tensorflow:Performing full trace on next step.
> I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcupti.so.8.0. LD_LIBRARY_PATH: /usr/local/cuda-8.0/lib64:
> F tensorflow/core/platform/default/gpu/cupti_wrapper.cc:59] Check failed: ::tensorflow::Status::OK() == (::tensorflow::Env::Default()->GetSymbolFromLibrary( GetDsoHandle(), kName, &f)) (OK vs. Not found: /home/dawid/tensorflow/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: cuptiActivityRegisterCallbacks)could not find cuptiActivityRegisterCallbacksin libcupti DSO
> Aborted (core dumped)
> 

few lines earlier:

> I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 960, pci bus id: 0000:01:00.0)
> E tensorflow/stream_executor/cuda/cuda_driver.cc:1002] failed to allocate 3.94G (4232314880 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY

However, my tensorflow works in other projects.

Where should I look?

**Comment by smolendawid** [comment]
I have copied everything (3 .so files) from 
/usr/local/cuda-8.0/extras/CUPTI/lib64/
to 
/usr/local/cuda-8.0/lib64/

and it works

**Comment by prabhuiitdhn** [comment]
Check your libcupti.so.8.0 file in "/usr/local/cuda-8.0/extra/CUPTI/lib64/" path. If exists, copy the whole libcupti.* file in LD_LIBRARY_PATH

> > cd /usr/local/cuda-8.0/extra/CUPTI/lib64/
> > sudo cp /usr/local/cuda-8.0/extra/CUPTI/lib64/libcupti* /directory/of/LD/LIBRARY/PATH/

Hope this will work fine, for me It worked.
Good luck !!
