### ISSUE TITLE
ResourceExhaustedError: OOM when allocating tensor of shape [171164,200] and type float

### ISSUE THREAD

**Issue by shery91** [google/seq2seq#322]
I was running on colaboratory all day and it was working fine and all of a sudden it started giving me this error. I tried to reduce the batch size and the input size ( text classification task  with embedding, CNN and LSTM Layer and 2 Dense by Keras) but it was all in vain. what should I do next? 
This is my model : 

Layer (type)                    Output Shape         Param #     Connected to                     
input_45 (InputLayer)           (None, 100)          0                                            
input_46 (InputLayer)           (None, 100)          0                                            
input_47 (InputLayer)           (None, 100)          0                                            
embedding_45 (Embedding)        (None, 100, 200)     34232800    input_45[0][0]                   
embedding_46 (Embedding)        (None, 100, 200)     34232800    input_46[0][0]                   
embedding_47 (Embedding)        (None, 100, 200)     34232800    input_47[0][0]                   
conv1d_45 (Conv1D)              (None, 99, 32)       12832       embedding_45[0][0]               
conv1d_46 (Conv1D)              (None, 97, 32)       25632       embedding_46[0][0]               
conv1d_47 (Conv1D)              (None, 93, 32)       51232       embedding_47[0][0]               
dropout_45 (Dropout)            (None, 99, 32)       0           conv1d_45[0][0]                  
dropout_46 (Dropout)            (None, 97, 32)       0           conv1d_46[0][0]                  
dropout_47 (Dropout)            (None, 93, 32)       0           conv1d_47[0][0]                  
max_pooling1d_45 (MaxPooling1D) (None, 49, 32)       0           dropout_45[0][0]                 
max_pooling1d_46 (MaxPooling1D) (None, 48, 32)       0           dropout_46[0][0]                 
max_pooling1d_47 (MaxPooling1D) (None, 46, 32)       0           dropout_47[0][0]                 
lstm_37 (LSTM)                  (None, 49, 40)       11680       max_pooling1d_45[0][0]           
lstm_38 (LSTM)                  (None, 48, 40)       11680       max_pooling1d_46[0][0]           
lstm_39 (LSTM)                  (None, 46, 40)       11680       max_pooling1d_47[0][0]           
flatten_45 (Flatten)            (None, 1960)         0           lstm_37[0][0]                    
flatten_46 (Flatten)            (None, 1920)         0           lstm_38[0][0]                    
flatten_47 (Flatten)            (None, 1840)         0           lstm_39[0][0]                    
concatenate_15 (Concatenate)    (None, 5720)         0 
flatten_45[0][0]                 
flatten_46[0][0]                 
flatten_47[0][0]                 
dense_37 (Dense)                (None, 30)           171630      concatenate_15[0][0]             
dense_38 (Dense)                (None, 20)           620         dense_37[0][0]                   
dense_39 (Dense)                (None, 1)            21          dense_38[0][0]                   

**and this is the error** 
ResourceExhaustedError                    Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1326     try:
-> 1327       return fn(*args)
   1328     except errors.OpError as e:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1311       return self._call_tf_sessionrun(
-> 1312           options, feed_dict, fetch_list, target_list, run_metadata)
   1313 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1419             self._session, options, feed_dict, fetch_list, target_list,
-> 1420             status, run_metadata)
   1421 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    515             compat.as_text(c_api.TF_Message(self.status.status)),
--> 516             c_api.TF_GetCode(self.status.status))
    517     # Delete the underlying status object from memory otherwise it stays alive

ResourceExhaustedError: OOM when allocating tensor of shape [171164,200] and type float
	 [[Node: training_12/Adam/zeros = Const[dtype=DT_FLOAT, value=Tensor<type: float shape: [171164,200] values: [0 0 0]...>, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

ResourceExhaustedError                    Traceback (most recent call last)
<ipython-input-22-99441bca8517> in <module>()
    116 
    117 model.fit([X_train, X_train, X_train], Y_train, epochs=8, batch_size=24 ,
--> 118           validation_data=[[X_val,X_val,X_val], Y_val])
    119 
    120 model.save("model.h5")

/usr/local/lib/python3.6/dist-packages/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
   1703                               initial_epoch=initial_epoch,
   1704                               steps_per_epoch=steps_per_epoch,
-> 1705                               validation_steps=validation_steps)
   1706 
   1707     def evaluate(self, x=None, y=None,

/usr/local/lib/python3.6/dist-packages/keras/engine/training.py in _fit_loop(self, f, ins, out_labels, batch_size, epochs, verbose, callbacks, val_f, val_ins, shuffle, callback_metrics, initial_epoch, steps_per_epoch, validation_steps)
   1234                         ins_batch[i] = ins_batch[i].toarray()
   1235 
-> 1236                     outs = f(ins_batch)
   1237                     if not isinstance(outs, list):
   1238                         outs = [outs]

/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py in __call__(self, inputs)
   2478             feed_dict[tensor] = value
   2479         fetches = self.outputs + [self.updates_op] + self.fetches
-> 2480         session = get_session()
   2481         updated = session.run(fetches=fetches, feed_dict=feed_dict,
   2482                               **self.session_kwargs)

/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py in get_session()
    198                     v._keras_initialized = True
    199                 if uninitialized_vars:
--> 200                     session.run(tf.variables_initializer(uninitialized_vars))
    201     # hack for list_devices() function.
    202     # list_devices() function is not available under tensorflow r1.3.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    903     try:
    904       result = self._run(None, fetches, feed_dict, options_ptr,
--> 905                          run_metadata_ptr)
    906       if run_metadata:
    907         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1138     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1139       results = self._do_run(handle, final_targets, final_fetches,
-> 1140                              feed_dict_tensor, options, run_metadata)
   1141     else:
   1142       results = []

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1319     if handle is None:
   1320       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1321                            run_metadata)
   1322     else:
   1323       return self._do_call(_prun_fn, handle, feeds, fetches)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1338         except KeyError:
   1339           pass
-> 1340       raise type(e)(node_def, op, message)
   1341 
   1342   def _extend_graph(self):

ResourceExhaustedError: OOM when allocating tensor of shape [171164,200] and type float
	 [[Node: training_12/Adam/zeros = Const[dtype=DT_FLOAT, value=Tensor<type: float shape: [171164,200] values: [0 0 0]...>, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'training_12/Adam/zeros', defined at:
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/usr/local/lib/python3.6/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2822, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-22-99441bca8517>", line 118, in <module>
    validation_data=[[X_val,X_val,X_val], Y_val])
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1682, in fit
    self._make_train_function()
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 992, in _make_train_function
    loss=self.total_loss)
  File "/usr/local/lib/python3.6/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/optimizers.py", line 457, in get_updates
    ms = [K.zeros(K.int_shape(p), dtype=K.dtype(p)) for p in params]
  File "/usr/local/lib/python3.6/dist-packages/keras/optimizers.py", line 457, in <listcomp>
    ms = [K.zeros(K.int_shape(p), dtype=K.dtype(p)) for p in params]
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 693, in zeros
    v = tf.zeros(shape=shape, dtype=tf_dtype, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/array_ops.py", line 1601, in zeros
    output = fill(shape, constant(zero, dtype=dtype), name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 2583, in fill
    "Fill", dims=dims, value=value, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3290, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

ResourceExhaustedError (see above for traceback): OOM when allocating tensor of shape [171164,200] and type float
	 [[Node: training_12/Adam/zeros = Const[dtype=DT_FLOAT, value=Tensor<type: float shape: [171164,200] values: [0 0 0]...>, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Comment by shery91** [comment]
Issue is solved by 
def get_session(gpu_fraction=0.3):
    '''Assume that you have 6GB of GPU memory and want to allocate ~2GB'''

    num_threads = os.environ.get('OMP_NUM_THREADS')
    gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=gpu_fraction)

    if num_threads:
        return tf.Session(config=tf.ConfigProto(
            gpu_options=gpu_options, intra_op_parallelism_threads=num_threads))
    else:
        return tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))
config = tf.ConfigProto( device_count = {'GPU': 1 , 'CPU': 8} )
sess = tf.Session(config=config) 
KTF.set_session(get_session())

**Comment by utkarshsharma1** [comment]
> Issue is solved by
> def get_session(gpu_fraction=0.3):
> '''Assume that you have 6GB of GPU memory and want to allocate ~2GB'''
> 
> ```
> num_threads = os.environ.get('OMP_NUM_THREADS')
> gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=gpu_fraction)
> 
> if num_threads:
>     return tf.Session(config=tf.ConfigProto(
>         gpu_options=gpu_options, intra_op_parallelism_threads=num_threads))
> else:
>     return tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))
> ```
> 
> config = tf.ConfigProto( device_count = {'GPU': 1 , 'CPU': 8} )
> sess = tf.Session(config=config)
> KTF.set_session(get_session())

What is KTF ?
